# Generated by Django 2.1.1 on 2018-11-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_remove_hr_registration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_registration',
            name='phone',
            field=models.IntegerField(default=91),
        ),
    ]
