# Generated by Django 2.1.1 on 2018-11-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_hr_registration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_registration',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hr_registration',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_registration',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
