# Generated by Django 2.1.1 on 2018-11-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_auto_20181127_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('idno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=60)),
                ('Add', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='HR_Registration',
        ),
    ]
