# Generated by Django 2.1.1 on 2018-11-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_auto_20181127_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_Registration',
            fields=[
                ('idno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
    ]
